# Generated by Django 4.2.4 on 2023-09-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iddb',
            fields=[
                ('pmcid', models.CharField(default=None, max_length=25, primary_key=True, serialize=False)),
                ('isValidId', models.BooleanField(default=False)),
                ('degree', models.IntegerField(blank=True, default=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='docdb',
            fields=[
                ('pmcid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='litexplorer.iddb')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('abstract', models.TextField(blank=True, default=None, null=True)),
                ('author', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='citedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ManyToManyField(related_name='child', to='litexplorer.iddb')),
                ('parent', models.ManyToManyField(related_name='parent', to='litexplorer.iddb')),
            ],
        ),
    ]
