# Generated by Django 2.1.15 on 2023-08-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmcid', models.CharField(default=None, max_length=25, unique=True)),
                ('pmid', models.CharField(default=None, max_length=25)),
                ('isValidId', models.BooleanField(default=False)),
                ('title', models.CharField(default=None, max_length=500)),
                ('abstract', models.TextField(default=None)),
                ('author', models.CharField(default=None, max_length=500)),
                ('degree', models.IntegerField(default=None)),
                ('parents', models.CharField(default=None, max_length=500)),
                ('children', models.CharField(default=None, max_length=500)),
                ('numparents', models.IntegerField(default=None)),
                ('numchildren', models.IntegerField(default=None)),
            ],
        ),
    ]
