# Generated by Django 2.1.15 on 2023-08-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litexplorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdb',
            name='abstract',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='children',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='degree',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='numchildren',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='numparents',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='parents',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='pmcid',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='pmid',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
