# Generated by Django 4.2.4 on 2023-09-01 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litexplorer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citedb',
            name='child',
        ),
        migrations.RemoveField(
            model_name='citedb',
            name='parent',
        ),
        migrations.AddField(
            model_name='citedb',
            name='child',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='litexplorer.iddb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citedb',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='litexplorer.iddb'),
            preserve_default=False,
        ),
    ]
