# Generated by Django 4.2.4 on 2023-08-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litexplorer', '0002_auto_20230829_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdb',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='children',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='parents',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
