# Generated by Django 4.2.4 on 2023-09-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litexplorer', '0002_remove_citedb_child_remove_citedb_parent_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='citedb',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_migration_host_combination'),
        ),
    ]
