# Generated by Django 4.2.4 on 2023-08-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litexplorer', '0003_alter_docdb_author_alter_docdb_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docdb',
            name='author',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='children',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='parents',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='docdb',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
