# Generated by Django 4.2.4 on 2023-09-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litexplorer', '0003_citedb_unique_migration_host_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citedb',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child+', to='litexplorer.iddb'),
        ),
        migrations.AlterField(
            model_name='citedb',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent+', to='litexplorer.iddb'),
        ),
    ]
